name: Publish to PyPi
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build and publish package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Build package
        run: make build
      - name: Publish package
        run: make upload
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD }}
